templates: add ui for possible matches
inspirehep/inspirehep-search-js pull request #63
Opened 2018-01-16 13:49 UTC by Dinika

Signed-off-by: Dinika <dinika.saxena@cern.ch>

2018-01-22 10:18 UTC, ammirate commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
> +                    <div ng-if="record._source._extra_data.record_matches.length <= 5">
The matched identifiers will be from now in ``record._source._extra_data.matches.fuzzy``

2018-01-22 10:19 UTC, ammirate commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
> +                      No Match Found
"None of these"

2018-01-22 10:21 UTC, ammirate requested changes
Apart from the new field for the fuzzy matches ids, we have to add the logic to the button to resume the workflow.

2018-01-22 11:02 UTC, ammirate commented
For the button that resumes the workflow, what it should do is:
* prepare the body of the request as ``{'match_recid': id}``
* send a POST request to ``'/api/holdingpen/<<WORKFLOW_ID>>/action/resolve'`` with the body defined above.

2018-01-23 09:23 UTC, drjova commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
> +                          <input id="{{match}}" name="possible-matches" type="radio">
hmm shouldn't be ``<input ng-model="match" ... />``? (Maybe I'm missing something ☺️)

2018-01-23 09:28 UTC, drjova commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
> +                        <p class="small-text">Showing 5 out of {{ (record._source._extra_data.record_matches.length-1) }} possible matches</p>
IMHO we should remove the ``-1`` in ``record._source._extra_data.record_matches.length``. Shall we also remove  the hardcoded ``5``? ☺️

2018-02-01 14:18 UTC, closed without merging