templates: fix possible matches UI for pub_info & abstract
inspirehep/inspirehep-search-js pull request #82
Opened 2018-04-17 14:09 UTC by Dinika

User Story - [Inspire-435](https://its.cern.ch/jira/browse/INSPIR-435)
Following things were improved:

- the public_notes is always displayed as a list element (no bullet points though) even when there is only one public-note
- If there is one author, number of authors is not displayed. Same applies for the possible matches for a submitted record (also, `author` is changed to all small alphabets - just a small change)
- For records that do not have journal-title in publication_info, the pubinfo_freetext field is displayed to be consistent with the information displayed on [literature UI](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/theme/templates/inspirehep_theme/format/record/Publication_info.tpl) 

![screenshot from 2018-04-18 14-39-02](https://user-images.githubusercontent.com/11242410/38932590-f78a8a32-4316-11e8-86c5-e53c081d72d3.png)

Signed-off-by: Dinika Saxena <dinika.saxena@cern.ch>

2018-04-17 14:18 UTC, drjova commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results_details_hep.html
> +<div>
we should remove this :)

2018-04-17 14:20 UTC, drjova commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details.html
> +              <br>
do we need the ``br`` here?

2018-04-17 15:19 UTC, drjova approved these changes

2018-04-17 16:39 UTC, drjova commented
DO NOT MERGE

2018-04-18 07:21 UTC, harunurhan requested changes

2018-04-18 07:21 UTC, harunurhan commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/details/details.html
> +            <div ng-if="vm.record.metadata.publication_info" class="record-pub-info">
`&& vm.record.metadata.publication_info[0]`

2018-04-18 07:21 UTC, harunurhan commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results_details_hep.html
> +      <span ng-if="record._source.metadata.public_notes.length === 1" class="regular-text">{{record._source.metadata.public_notes[0].value}}</span>
I don't think doing a special case for `length === 1` is necessary, why not display it as `ul` with single `li`?

2018-04-18 07:21 UTC, harunurhan commented on src/inspirehep-holdingpen-js/templates/inspirehep-holdingpen-js/results/results.html
> +                            <dt ng-if="match.publication_info && (match.publication_info[0].journal_title || match.publication_info[0].pubinfo_freetext) ">Published In</dt>
`&& vm.record.metadata.publication_info[0]` before accessing the item at `0`.

2018-04-18 12:58 UTC, harunurhan approved these changes

2018-04-18 13:12 UTC, merged